---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baserow-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 5Gi
