---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: baserow-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: baserow-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_HOST: postgres-rw.database.svc.cluster.local
        DATABASE_NAME: baserow
        DATABASE_USER: "{{ `{{ .POSTGRES_USER }}` }}"
        DATABASE_PASSWORD: "{{ `{{ .POSTGRES_PASS }}` }}"
        DATABASE_PORT: "5432"
        EMAIL_SMTP: "true"
        EMAIL_SMTP_HOST: smtp.fastmail.com
        EMAIL_SMTP_PORT: "465"
        EMAIL_SMTP_USER: "{{ `{{.smtp_username}}` }}"
        EMAIL_SMTP_PASSWORD: "{{ `{{.smtp_password}}` }}"
        EMAIL_SMTP_USE_TLS: "true"

        # Postgres Init
        POSTGRES_DB: baserow
        POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        POSTGRES_SUPER_PASS: "{{ `{{ .POSTGRES_SUPER_PASS }}` }}"
        POSTGRES_SUPER_USER: "{{ `{{ .POSTGRES_SUPER_USER }}` }}"
        POSTGRES_PASS: "{{ `{{ .POSTGRES_PASS }}` }}"
        POSTGRES_USER: "{{ `{{ .POSTGRES_USER }}` }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
        conversionStrategy: Default
        decodingStrategy: None
    - extract:
        key: Fastmail SMTP
        conversionStrategy: Default
        decodingStrategy: None
      rewrite:
        - regexp:
            source: "(.*)"
            target: "smtp_$1"
