---
app-template:
  controller:
    type: cronjob
    cronjob:
      concurrencyPolicy: Forbid
      schedule: "@hourly"
  restartPolicy: OnFailure
  image:
    repository: ghcr.io/onedr0p/kubernetes-kubectl
    tag: 1.27.1@sha256:2067b52145cdcb99b1db4e92fa114babc0a8a91e08711cbe1aae05ba5a277dd9
  command: ["/bin/bash", "/app/cloudflare-ddns.sh"]
  envFrom:
    - secretRef:
        name: cloudflare-ddns-secrets
  service:
    main:
      enabled: false
  persistence:
    config:
      enabled: true
      type: configMap
      name: cloudflare-ddns-configmap
      subPath: cloudflare-ddns.sh
      mountPath: /app/cloudflare-ddns.sh
      defaultMode: 0775
      readOnly: true
