---
app-template:
  controller:
    type: cronjob
    cronjob:
      concurrencyPolicy: Forbid
      schedule: "@hourly"
  restartPolicy: OnFailure
  image:
    repository: ghcr.io/onedr0p/kubernetes-kubectl
    tag: 1.26.0@sha256:6ee3353da3495bc99d73af29a4495bb95570e31e71579cfce719c4123882723d
  command: ["/bin/bash", "/app/cloudflare-ddns.sh"]
  envFrom:
    - secretRef:
        name: cloudflare-ddns-secret
  service:
    main:
      enabled: false
  persistence:
    config:
      enabled: true
      type: secret
      name: cloudflare-ddns-configmap
      subPath: cloudflare-ddns.sh
      mountPath: /app/cloudflare-ddns.sh
      defaultMode: 0775
      readOnly: true
