---
app-template:
  image:
    repository: qmcgaw/ddns-updater
    tag: latest
  env:
    PUBLICIP_HTTP_PROVIDERS: ifconfig

  service:
    main:
      ports:
        http:
          port: 8000
  persistence:
    config:
      enabled: true
      type: configMap
      name: ddns-updater-config
      subPath: config.json
      mountPath: /data/config.json
      defaultMode: 0775
      readOnly: true
