---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Home Assistant
        RADARR__API_KEY: "{{ `{{ .API_KEY }}` }}"
  dataFrom:
    - extract:
        key: Radarr
        conversionStrategy: Default
        decodingStrategy: None
