app-template:
    ingress:
        main:
            annotations:
                external-dns.alpha.kubernetes.io/target: ENC[AES256_GCM,data:cXbJjKyshW7KjEfSB4Bu,iv:W/JWvCL+YgWpRISeZDRHRTkVoI0B8EeokK/aSnEG3ys=,tag:qR2fezvsLy9NlXO5dEIeWA==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:qfdb1NCOhhGefif24reJ,iv:/2ILJDlB5bQRKEv2M+rMWWHmyzJv4mV19PtliVAPI8c=,tag:Gku4G1HRERu8genQHDFneQ==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:ow==,iv:X0heplri69J4MEV9mKHDS4YjzjhaA0jiflHiCJ6AQIc=,tag:cMlI7KdSsK1Xc0rd0kh1KA==,type:str]
                      pathType: ENC[AES256_GCM,data:ij2JwLgB,iv:Javn5Rpkqbzv6BpsOa2S32OWEyAPdrOjfaxcUtBXwOs=,tag:viEMNtVS6NYSR+anXjIUow==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:NL/R1zOn3E6MSy4vGatd,iv:+02RmqXcf+nXcvosNMACd+K7hdwxZoMtvYk1lc6OOh8=,tag:57kGN64NzHqp8NkXutTACA==,type:str]
    addons:
        codeserver:
            ingress:
                hosts:
                    - host: ENC[AES256_GCM,data:FMzTD0hU0G8+MzI4ZnHoiwfs,iv:ZuDsfMYE9lrWSXXgseBRysgGr+okt8gI5wzzJnLQJ0k=,tag:GWrzW+jGYIEixWTr8Ag2Jw==,type:str]
                      paths:
                        - path: ENC[AES256_GCM,data:mQ==,iv:AClMxVDS9VpKVUXSpDWcZpmx9oV4NmpYTZd/IEp0AWE=,tag:Gfjux9ByCEDX4ox2xs4wKg==,type:str]
                          pathType: ENC[AES256_GCM,data:+jlkjAiN,iv:26wIFgfaaOPEvXVuAlnY3UAaNggVdeV/clApLSt0jEk=,tag:F5bB6qzQGgb9APxESEA5yw==,type:str]
                tls:
                    - hosts:
                        - ENC[AES256_GCM,data:0UTBeh1pxbPJMKQ90GA/HjA0U5Y=,iv:/AZJWIVjISVFXTAuKDhO3V6W1yWpSTjYXHg5SQfQVVM=,tag:MT6f3XvMGjjEgI5z9vyywQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQ3FjYzlEeDlNNUwvVnF2
            WjJDSEdqSDZsQUNWU25yRlQrZjMwa0plUkhjCnd5K2ZNeVNLbkF3R3dMeVJlT3pT
            VFhxVTdrY1hna05GUE9FM3V0RUdDMGsKLS0tIEF0YzNEd0xhTzRGbnpVVTU1QWw0
            QU9qdVJqczE4T2l4czFCODlnN25UYUUKw2o1unfLCsDANtSJ5WgCbWbB9sevHngk
            IVauZEXHuWENa5r/n3vUNl20GFfRiGMfTOcnFyY0yOawx6BMY0AXEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-23T20:37:42Z"
    mac: ENC[AES256_GCM,data:mJDm+wGz2M2t/tplMXcoy5LEWnlo32wJ27DrSfUfOdBHUn+3iWjffmef4aIXwwxr29M04m4RX3mXk/97R1K09MR/9/xUBowsWscbHchPG14u+ghqBeq5ALBCtVd+u3Qv5C7npAy3qVdHpiLAGQ2R/hX8nY3URPctl+9ymQ+v06c=,iv:OhVzFRVWHKQXT2euPwJa8D8AtxkdWYx1sSMxSqmq0wk=,tag:Pa5at9dGkqSM4OofXnDyag==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
