app-template:
    ingress:
        main:
            #ENC[AES256_GCM,data:FMwZz6WC9HGq0usmiA==,iv:ag22t2sU3XyCy88Br10GJ0LsS7YFwctVKLnyn6GtQnE=,tag:1+yQA5x7EV/IEw8CVQc70w==,type:comment]
            #ENC[AES256_GCM,data:KpPcD9bueq4a9vaDRv8uj62pi8WFR3p0V76w66CJA5WisRp4w/QIuXoGgvzJN+5EImPMiw==,iv:61JyH1Rlp/CoUSndZpf9SIypjQUcZ9WLnbfngnPeheE=,tag:+y9XelEGiCXydQchUeRkEw==,type:comment]
            hosts:
                - host: ENC[AES256_GCM,data:qfdb1NCOhhGefif24reJ,iv:/2ILJDlB5bQRKEv2M+rMWWHmyzJv4mV19PtliVAPI8c=,tag:Gku4G1HRERu8genQHDFneQ==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:ow==,iv:X0heplri69J4MEV9mKHDS4YjzjhaA0jiflHiCJ6AQIc=,tag:cMlI7KdSsK1Xc0rd0kh1KA==,type:str]
                      pathType: ENC[AES256_GCM,data:ij2JwLgB,iv:Javn5Rpkqbzv6BpsOa2S32OWEyAPdrOjfaxcUtBXwOs=,tag:viEMNtVS6NYSR+anXjIUow==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:NL/R1zOn3E6MSy4vGatd,iv:+02RmqXcf+nXcvosNMACd+K7hdwxZoMtvYk1lc6OOh8=,tag:57kGN64NzHqp8NkXutTACA==,type:str]
    addons:
        codeserver:
            ingress:
                hosts:
                    - host: ENC[AES256_GCM,data:FMzTD0hU0G8+MzI4ZnHoiwfs,iv:ZuDsfMYE9lrWSXXgseBRysgGr+okt8gI5wzzJnLQJ0k=,tag:GWrzW+jGYIEixWTr8Ag2Jw==,type:str]
                      paths:
                        - path: ENC[AES256_GCM,data:mQ==,iv:AClMxVDS9VpKVUXSpDWcZpmx9oV4NmpYTZd/IEp0AWE=,tag:Gfjux9ByCEDX4ox2xs4wKg==,type:str]
                          pathType: ENC[AES256_GCM,data:+jlkjAiN,iv:26wIFgfaaOPEvXVuAlnY3UAaNggVdeV/clApLSt0jEk=,tag:F5bB6qzQGgb9APxESEA5yw==,type:str]
                tls:
                    - hosts:
                        - ENC[AES256_GCM,data:0UTBeh1pxbPJMKQ90GA/HjA0U5Y=,iv:/AZJWIVjISVFXTAuKDhO3V6W1yWpSTjYXHg5SQfQVVM=,tag:MT6f3XvMGjjEgI5z9vyywQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQ3FjYzlEeDlNNUwvVnF2
            WjJDSEdqSDZsQUNWU25yRlQrZjMwa0plUkhjCnd5K2ZNeVNLbkF3R3dMeVJlT3pT
            VFhxVTdrY1hna05GUE9FM3V0RUdDMGsKLS0tIEF0YzNEd0xhTzRGbnpVVTU1QWw0
            QU9qdVJqczE4T2l4czFCODlnN25UYUUKw2o1unfLCsDANtSJ5WgCbWbB9sevHngk
            IVauZEXHuWENa5r/n3vUNl20GFfRiGMfTOcnFyY0yOawx6BMY0AXEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-19T18:49:40Z"
    mac: ENC[AES256_GCM,data:jZYpujFW23Q0zsVtTyxM/f9TR5RRR8nSjm3cV6G/Psj8batuGWaVGKNjqPdnkjzHQujop73OmwW8pBi2EyVy6mmgjvBvc34HVq16Z5SLGV9tRR7dWf2/OGjHVJPDWpfGeXWtxWKcaHeHMayHcBfHnbLNu4sd6JUNIcFv5Q7+xbA=,iv:6FrZqVtsM0Vu1eC5RzJJw3XQhsjhu0HeawPL9umAivA=,tag:QgWG0gNupFoTGd9JW3r5WA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
