---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vodafone-station-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vodafone-station-exporter-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        vodafoneStationUrl: "http://192.168.100.1"
        vodafoneStationPassword: "{{ `{{ .password }}` }}"
  dataFrom:
    - extract:
        key: Vodafone Station
        conversionStrategy: Default
        decodingStrategy: None
