---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
  labels:
    argocd.argoproj.io/secret-type: Opaque
stringData:
  token: {{ .Values.onepassword.token }}

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        Homelab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
