---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tatort-bot
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tatort-bot-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        # CHAT_ID, BOT_TOKEN
        key: Tatort Telegram
