---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: valheim-config
  labels:
    app.kubernetes.io/name: valheim
spec:
  storageClassName: longhorn
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: valheim-server
  labels:
    app.kubernetes.io/name: valheim
spec:
  storageClassName: longhorn
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
