---
longhorn:
  persistence:
    defaultClassReplicaCount: 2
  defaultSettings:
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    backupTarget: nfs://192.168.30.4:/mnt/HDD/Backups/Longhorn
    orphanAutoDeletion: "True"
  longhornManager:
    tolerations:
      - operator: "Exists"
  longhornDriver:
    tolerations:
      - operator: "Exists"
  longhornRecoveryBackend:
    replicas: 0
    tolerations:
      - operator: "Exists"
  longhornConversionWebhook:
    replicas: 0
  longhornAdmissionWebhook:
    replicas: 0
