---
longhorn:
  persistence:
    defaultClassReplicaCount: 2
  defaultSettings:
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    backupTarget: nfs://192.168.30.4:/mnt/HDD/Backups/Longhorn
  longhornManager:
    tolerations:
      - operator: "Exists"
  longhornDriver:
    tolerations:
      - operator: "Exists"
  longhornRecoveryBackend:
    tolerations:
      - operator: "Exists"
