app-template:
    ingress:
        main:
            hosts:
                - host: ENC[AES256_GCM,data:hxtlgkxxmdbLavG5YJrftHwLDg==,iv:reYzK8zhmBjink17X+u/HS0ZGffQtjRWUDBAul9+H2c=,tag:1oqf0wAIWcN/n9VxUJtFpA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:tQ==,iv:/KPJ0Scq5848GPg0mRZYYbytNuIhKpCgp0fqxbb1wOY=,tag:BOJyf7es38r2VJiZonlPig==,type:str]
                      pathType: ENC[AES256_GCM,data:DJIVdBCo,iv:0ixJBmDIAVUaFHFW+B5yul2ZVJYgqjtpFbWm1j7llw0=,tag:QU46Xqa/4bkmxVcJ4WZeTw==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:uLAiEbii8k9tWe9rjUxwg1cpwQ==,iv:pdG1Ql1DP503zBc3l2ExkEetJ0X6ftwBSwzXHAeiyac=,tag:dyqWgynHafq+h2edGDNFag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSWVBeUN3cU9YcTl5cUVB
            Y1I0S3FGemQ1RFg4UTBTdWF5eUxkQzc1SXl3CnU2UGRPT2JqSDBUUlYvd2E4L1Fy
            YkhCZlBpSTRjNkJ5Y1lHaS9OZDdMVDgKLS0tIDdZblZJVzlHaEE2ZHRibnpSbGY3
            YklFV0ZXbE9YYnd5THJwYUUwQUtCUmcKKDsKeQPxGFl8ylA2HXbkBfHL9IS/vrC6
            X8LiGfVCsB/EkMufP4SHw5TrgREoZGr5rxUx5CcbwQF3kuB1qIipyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T20:25:38Z"
    mac: ENC[AES256_GCM,data:/x7gS11mXbNECDQEEQokNTAMwxCrOJ/6aRwzJyAfCc2t8Fqy73u4UCp73dCslOwlMXtv7Pvlt8n9m2QJKaJLHeWiWYU6bxVEGxjhJkXAbIQzKwZhxtnA8lC7548ZGa9iyTxqEeUVslskzwa66wNedA1wlSGgEdmPsQNHr86zntU=,iv:aAR5t4/qbrzfRi/KO0ypScSHIKOAGfX/lvqRq+XaR5k=,tag:4Jl5wEGh5aPCkzViAE2HOA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
