---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-config-v1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
