---
external-dns:
  interval: 5m
  logLevel: debug
  provider: cloudflare
  env:
    - name: CF_API_EMAIL
      valueFrom:
        secretKeyRef:
          name: external-dns-cloud-credentials
          key: email
    - name: CF_API_KEY
      valueFrom:
        secretKeyRef:
          name: external-dns-cloud-credentials
          key: api-key
  extraArgs:
    - --cloudflare-proxied
    - --managed-record-types=CNAME
    - --annotation-filter=external-dns.alpha.kubernetes.io/target
  policy: sync
  sources:
    - ingress
  txtPrefix: "k8s."
  txtOwnerId: "default"
  service:
    main:
      ports:
        http:
          port: 8000
  resources:
    requests:
      memory: 100Mi
      cpu: 25m
    limits:
      memory: 250Mi

  podAnnotations:
    secret.reloader.stakater.com/reload: external-dns-cloud-credentials

  serviceMonitor:
    enabled: true
