---
version: "3"

vars:
  TERRAFORM_DIR: "{{.ROOT_DIR}}/terraform"
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

env:
  KUBECONFIG: "{{.ANSIBLE_DIR}}/kubernetes/kubeconfig"

includes:
  cluster: .taskfiles/ClusterTasks.yml

tasks:
  default:
    silent: true
    cmds: ["task -l"]
