---
traefik:
  additionalArguments:
    - "--providers.kubernetesingress.ingressendpoint.publishedservice=networking/traefik"
    - "--experimental.plugins.theme-park.modulename=github.com/packruler/traefik-themepark"
    - "--experimental.plugins.theme-park.version=v1.2.2"
  service:
    spec:
      externalTrafficPolicy: Local
      loadBalancerIP: "192.168.40.2"
    annotations:
      metallb.universe.tf/allow-shared-ip: traefik

  experimental:
    plugins:
      enabled: true

  metrics:
    prometheus:
      serviceMonitor:
        enabled: true
      prometheusRule:
        rules:
          - alert: TraefikDown
            expr: up{job="traefik"} == 0
            for: 5m
            labels:
              context: traefik
              severity: critical
            annotations:
              summary: "Traefik Down"
              description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"

  ports:
    websecure:
      forwardedHeaders:
        trustedIPs:
          - 192.168.0.0/16
          - 10.0.0.0/8
          - 172.16.0.0/16
          - fc00::/7
    traefik:
      expose: true
    mailsecure:
      port: 465
      expose: true
      exposedPort: 465
    web:
      redirectTo: websecure
    metrics:
      expose: true

  providers:
    kubernetesCRD:
      allowExternalNameServices: true
      allowEmptyServices: true
    kubernetesIngress:
      allowExternalNameServices: true
      allowEmptyServices: true
      publishedService:
        enabled: true
  logs:
    general:
      level: DEBUG
    access:
      enabled: true
  ingressRoute:
    dashboard:
      enabled: false
