---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: freshrss-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: freshrss-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # freshrss
        ADMIN_EMAIL: "{{ `{{ .username }}` }}"
        ADMIN_PASSWORD: "{{ `{{ .password }}` }}"
        ADMIN_API_PASSWORD: "{{ `{{ .api_token }}` }}"
        POSTGRES_PASSWORD: "{{ `{{ .POSTGRESS_PASS }}` }}"
        # Postgres Init
        POSTGRES_DB: freshrss
        POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        POSTGRES_SUPER_PASS: "{{ `{{ .POSTGRES_SUPER_PASS }}` }}"
        POSTGRES_PASS: "{{ `{{ .POSTGRESS_PASS }}` }}"
        POSTGRES_USER: "{{ `{{ .POSTGRES_USER }}` }}"
  dataFrom:
    - extract:
        key: FreshRSS
        conversionStrategy: Default
        decodingStrategy: None
    - extract:
        key: cloudnative-pg
        conversionStrategy: Default
        decodingStrategy: None
