---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emqx
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: emqx-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        # admin_password, user_1_username, user_1_password
        key: EMQX
