---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-ddns-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CLOUDFLARE_RECORD_NAME: "ipv4.{{ `{{ .homelab_domain }}` }}"
        CLOUDFLARE_EMAIL: "{{ `{{ .username }}` }}"
        CLOUDFLARE_APIKEY: "{{ `{{ .GLOBAL_API_KEY }}` }}"
  dataFrom:
    - extract:
        key: Cloudflare
        conversionStrategy: Default
        decodingStrategy: None
    - extract:
        key: Homelab
        property: homelab_domain
        conversionStrategy: Default
        decodingStrategy: None
