---
app-template:
  controller:
    type: statefulset
    replicas: 1
    annotations:
      reloader.stakater.com/auto: "true"
  image:
    repository: ghcr.io/clempat/docker-vodafone-station-exporter
    tag: v0.0.2
  env:
    TZ: Europe/Berlin
  envFrom:
    - secretRef:
        name: vodafone-station-exporter-secrets
  service:
    main:
      ports:
        http:
          port: 9420
  serviceMonitor:
    main:
      enabled: true
      endpoints:
        - port: http
          scheme: http
          path: /metrics
          scrapeTimeout: 30s
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 500Mi
