---
app-template:
  controller:
    type: statefulset
    annotations:
      reloader.stakater.com/auto: "true"
  global:
    nameOverride: uptime-kuma
  image:
    repository: louislam/uptime-kuma
    tag: 1.23.0
  service:
    main:
      ports:
        http:
          port: 3001

  volumeClaimTemplates:
    - name: config
      mountPath: /app/data
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: longhorn
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        hajimari.io/icon: mdi:alert-circle-check
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 150Mi
