---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ddns-updater-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ddns-updater-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.json: |-
          {
            "settings": [
              {
                "provider": "cloudflare",
                "zone_identifier": "{{ `{{ .cloudflare_ZONE_ID }}` }}",
                "domain": "{{ `{{ .cloudflare_DOMAIN }}` }}",
                "host": "ipv4",
                "ttl": 600,
                "key": "{{ `{{ .cloudflare_GLOBAL_API_KEY }}` }}",
                "email": "{{ `{{ .cloudflare_username }}` }}", 
                "ip_version": "ipv4",
                "proxied": true
              }
            ]
          }
  dataFrom:
    - extract:
        key: Cloudflare
        conversionStrategy: Default
        decodingStrategy: None
      rewrite:
        - regexp:
            source: "(.*)"
            target: "cloudflare_$1"
