---
apiVersion: deviceplugin.intel.com/v1
kind: GpuDevicePlugin
metadata:
  name: intel-gpu-plugin
spec:
  image: intel/intel-gpu-plugin:0.26.1
  initImage: intel/intel-gpu-initcontainer:0.26.1
  logLevel: 2
  sharedDevNum: 2
  preferredAllocationPolicy: none

  nodeSelector:
    intel.feature.node.kubernetes.io/gpu: "true"
