locals {
  servers = module.proxmox.servers
  inventory = {
    kubernetes : {
      children : {
        master : {
          hosts : {
            for name in keys(local.servers) : name => { "ansible_host" : local.servers[name] }
          }
        }
      }
    }
  }
}
resource "local_file" "ansible_hosts_yaml" {
  content  = <<-DOC
    # Generated by Terraform mgmt configuration.
    ${yamlencode(local.inventory)}
          


  DOC
  filename = "../ansible/inventory/hosts.yaml"

}

output "debug" {
  value = local.inventory
}
