---
app-template:
  image:
    repository: mbround18/valheim
    tag: latest
  env:
    - name: NAME
      valueFrom:
        secretKeyRef:
          name: valheim-secret
          key: SERVER_NAME
    - name: WORLD
      valueFrom:
        secretKeyRef:
          name: valheim-secret
          key: WORLD_NAME
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: valheim-secret
          key: SERVER_PASS
    - name: WEBHOOK_URL
      valueFrom:
        secretKeyRef:
          name: valheim-secret
          key: DISCORD_WEBHOOK
    # - name: BACKUPS
    #   value: true
    - name: SERVER_PUBLIC
      value: false
    - name: TZ
      value: "Europe/Berlin"
    - name: SERVER_PORT
      value: 2456
    # - name: AUTO_UPDATE
    #   value: true
    # - name: AUTO_UPDATE_PAUSE_WITH_PLAYERS
    #   value: true
    - name: PUID
      value: 1003
    - name: PGID
      value: 1003
    # - name: VALHEIM_LOG_FILTER_CONTAINS_Spawned
    #   value: "Got character ZDOID from"
    # - name: ON_VALHEIM_LOG_FILTER_CONTAINS_Spawned
    #   value: '{ read l; l=$${l//*ZDOID from /}; l=$${l// :*/}; msg="Player $l connected."; curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$msg\"}" "$DISCORD_WEBHOOK"; }'
    # - name: DISCORD_MESSAGE
    #   value: "Starting Valheim Server"
    # - name: PRE_BOOTSTRAP_HOOK
    #   value: 'curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$$(eval echo $$DISCORD_MESSAGE)\"}" "$$DISCORD_WEBHOOK"'
    # - name: STATUS_HTTP
    #   value: "true"
    # - name: "BACKUPS_DIRECTORY"
    #   value: "/backups"
  persistence:
    backups:
      enabled: true
      type: nfs
      server: 192.168.30.4
      path: /mnt/HDD/Backups/valheim
      mountPath: /home/steam/backups
    config:
      enabled: true
      existingClaim: valheim-config
      mountPath: /home/steam/.config/unity3d/IronGate/Valheim
    server:
      enabled: true
      existingClaim: valheim-server
      mountPath: /home/steam/valheim
  service:
    main:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 192.168.40.4
      ports:
        http:
          enabled: false
        valheim-1:
          enabled: true
          port: 2456
          protocol: UDP
          targetPort: 2456
        valheim-2:
          enabled: false
          port: 2457
          protocol: UDP
          targetPort: 2457
        valheim-3:
          enabled: false
          port: 2458
          protocol: UDP
          targetPort: 2458
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: bell-outline
  nodeSelector:
    intel.feature.node.kubernetes.io/gpu: "true"
  resources:
    limits:
      gpu.intel.com/i915: 1
      memory: "7Gi"
    requests:
      gpu.intel.com/i915: 1
      memory: "5Gi"
