---
app-template:
  controller:
    replicas: 1
    type: statefulset
    annotations:
      reloader.stakater.com/auto: "true"
  image:
    repository: mbround18/valheim
    tag: latest
  restartPolicy: Never
  probes:
    liveness:
      enabled: true
      type: UDP
    readiness:
      enabled: true
      type: UDP
    startup:
      enabled: true
      type: UDP
  env:
    - name: NAME
      valueFrom:
        secretKeyRef:
          name: valheim-secret
          key: SERVER_NAME
    - name: WORLD
      valueFrom:
        secretKeyRef:
          name: valheim-secret
          key: WORLD_NAME
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: valheim-secret
          key: SERVER_PASS
    - name: WEBHOOK_URL
      valueFrom:
        secretKeyRef:
          name: valheim-secret
          key: DISCORD_WEBHOOK
    - name: BACKUPS
      value: true
    - name: PUBLIC
      value: false
    - name: TZ
      value: "Europe/Berlin"
    - name: PORT
      value: 2456
    - name: AUTO_UPDATE
      value: true
    - name: AUTO_UPDATE_PAUSE_WITH_PLAYERS
      value: true
    - name: PGID
      value: 1003
    - name: PUID
      value: 1003
    - name: HTTP_PORT
      value: 80
    - name: TYPE
      value: BepInEx
    - name: MODS
      value: |
        https://github.com/Astropilot/ValheimTooler/releases/download/v1.8.0/ValheimTooler-1.8.0_BepInExMod.zip
  persistence:
    backups:
      enabled: true
      type: nfs
      server: 192.168.30.4
      path: /mnt/HDD/Backups/valheim
      mountPath: /home/steam/backups
    config:
      enabled: true
      existingClaim: valheim-config
      mountPath: /home/steam/.config/unity3d/IronGate/Valheim
    server:
      enabled: true
      existingClaim: valheim-server
      mountPath: /home/steam/valheim
  service:
    main:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 192.168.40.4
      ports:
        http:
          port: 80
        valheim-1:
          enabled: true
          port: 2456
          protocol: UDP
          targetPort: 2456
        valheim-2:
          enabled: true
          port: 2457
          protocol: UDP
          targetPort: 2457
        valheim-3:
          enabled: true
          port: 2458
          protocol: UDP
          targetPort: 2458
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: bell-outline

  serviceAccount:
    name: "tailscale"

  sidecars:
    ts-sidecar:
      image: "ghcr.io/tailscale/tailscale:v1.42.0"
      env:
        # Store the state in a k8s secret
      - name: TS_KUBE_SECRET
        value: "tailscale-auth"
      - name: TS_USERSPACE
        value: "false"
      - name: TS_AUTHKEY
        valueFrom:
          secretKeyRef:
            name: tailscale-auth
            key: TS_AUTHKEY
            optional: true
      securityContext:
        capabilities:
          add:
          - NET_ADMIN
  nodeSelector:
    intel.feature.node.kubernetes.io/gpu: "true"
  resources:
    limits:
      gpu.intel.com/i915: 1
      memory: "7Gi"
    requests:
      gpu.intel.com/i915: 1
      memory: "5Gi"
