---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: external-dns-cloud-credentials
    creationPolicy: Owner
  data:
    - secretKey: email
      remoteRef:
        key: Cloudflare
        property: username
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: api-key
      remoteRef:
        key: Cloudflare
        property: GLOBAL_API_KEY
        conversionStrategy: Default
        decodingStrategy: None
