---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smb-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  data:
    - secretKey: username
      remoteRef:
        key: SMB
        property: username
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: password
      remoteRef:
        key: SMB
        property: password
        conversionStrategy: Default
        decodingStrategy: None
