---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas-smb-storage
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.30.4"
  csi.storage.k8s.io/node-stage-secret-name: "smb-secrets"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0700
  - file_mode=0700
  - uid=1003
  - gid=1006
