---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
  annotations:
    kyverno.io/ignore: "true"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14.5
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: local-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  bootstrap:
    recovery:
      source: &previous-cluster postgres-v2
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 15d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 4
      destinationPath: s3://postgresql/
      endpointURL: http://192.168.30.184:9000
      serverName: postgres-v3
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: s3-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: s3-secret-access-key
  # Note: externalClusters is needed when recovering from an existing cnpg cluster
  externalClusters:
    - name: *previous-cluster
      barmanObjectStore:
        wal:
          compression: bzip2
          maxParallel: 4
        destinationPath: s3://postgresql/
        endpointURL: http://192.168.30.184:9000
        s3Credentials:
          accessKeyId:
            name: cloudnative-pg-secret
            key: s3-access-key-id
          secretAccessKey:
            name: cloudnative-pg-secret
            key: s3-secret-access-key
