---
kubernetes:
  children:
    master:
      hosts:
        fuji-node-1:
          ansible_host: "192.168.40.41"
        nuc-node-1:
          ansible_host: "192.168.40.32"
      vars:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ansible_user: "ubuntu"
