---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config-v1
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
