---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - 192.168.40.200:9100
        - 192.168.30.199:9100
  metricsPath: /metrics
