app-template:
    ingress:
        main:
            hosts:
                - host: ENC[AES256_GCM,data:g/ocHAMwVuu+hiGyVfeXduhVAF8=,iv:QCgLCEbsYV6sC3hVYMuzWqd+YnlT+w5L4jFeGFRRVVM=,tag:byK09gMnivHoSWl4Ob4ckg==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:Lg==,iv:znYoeDRDIgqmPaLq+RVX7WzbNEcwd1djo6qRmy6zl4k=,tag:6HNLTcY4l/5JHIBtq2uAvQ==,type:str]
                      pathType: ENC[AES256_GCM,data:UjYm8toZ,iv:YXsgtMgSHzrYJbMiinKJgLIUhI2y7m1mziEKvlO0htk=,tag:1IsDM+teifpEJDKY/fK0dg==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:rkpzRt6Ok3tcZS/gObSqIDQKB1c=,iv:SV20umf/Nas7EMDcgPxS3dpL4YRQVUEdFAp69nM/rQs=,tag:symhe/CTBaffik9K9BWUTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNmhMTzN5aFVYeDl2RlZ3
            ek8xREttL0xETHYrQ0g2ejVUeHpqaFFqUUI0CjkyaG1ZY2p5NytQMGtDVkNUUG9Q
            R1c5Rk1JRmMvSEF4UVdmUlpwcmxQVjQKLS0tIDhTakVSN3J6R2Q0azQ4b2s5b0JF
            bi9pc21zSldTT0g5ZTJBdEhrMFk3NW8KROGNBuE/DyA1/m6fhG3qxxceo6eNSo4J
            Wq4ce7uxsRH1tDBD1KuxmCniK8hxnVe/kcaocy7VGBhmPHtZvh3JMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-11T21:08:08Z"
    mac: ENC[AES256_GCM,data:xH5n9emmYaNtyjBfNMB3iO/9/I4Peki08wBm7xeGzPsfyL1UzKA22eylqiqILg0FoQ0aQo9T9Re0E3bmchGtTJ9tH5CKhbPPZreANsRWZ+qSQeXvXblAfuVCBYMDX6BkVuhqOF0WmGc23Iyx7HgZg4POOsfHH8PfhU3hSuiTcJQ=,iv:RE7un9LIS7XATNJaNFDPJMgxQj/vB0J0iFzTfbDuwzs=,tag:LkTnay1U/3uvuGvwLs6MUg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
