---
app-template:
  global:
    nameOverride: syncthing
  image:
    repository: syncthing/syncthing
    tag: 1.23.4
  service:
    main:
      ports:
        http:
          port: 8384
    listdisc:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      loadBalancerIP: 192.168.40.8
      ports:
        discovery:
          enabled: true
          port: 21027
          protocol: UDP
        listen:
          enabled: true
          port: 22000
          protocol: TCP
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure

  persistence:
    data:
      enabled: true
      type: nfs
      server: 192.168.30.4
      path: /mnt/HDD/Syncthing
      mountPath: /var/syncthing

  resources:
    requests:
      cpu: 15m
      memory: 249Mi
    limits:
      memory: 1565Mi
