---
app-template:
  controller:
    strategy: RollingUpdate
  image:
    repository: ghcr.io/onedr0p/theme-park
    tag: 1.16.2@sha256:e90d483b3ca41920cae4466f06ccdb9d3cf0e44e656653f63e286da277a8db9e
  service:
    main:
      ports:
        http:
          port: 8080
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        hajimari.io/enable: "false"
  resources:
    requests:
      cpu: 5m
      memory: 10Mi
    limits:
      memory: 50Mi
