---
app-template:
  controller:
    strategy: RollingUpdate
  image:
    repository: ghcr.io/onedr0p/theme-park
    tag: 1.13.9@sha256:626343246c032fb712ba4b71d23a57595dcb579cbcfd46ed6b05dc30ecb0a2aa
  service:
    main:
      ports:
        http:
          port: 8080
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        hajimari.io/enable: "false"
  resources:
    requests:
      cpu: 5m
      memory: 10Mi
    limits:
      memory: 50Mi
