---
app-template:
  controller:
    strategy: RollingUpdate
  image:
    repository: ghcr.io/onedr0p/theme-park
    tag: 1.13.7@sha256:13793be3810cbad9305fe86f03e2fa320bf26270d5054e65e3e6044f106f39f0
  service:
    main:
      ports:
        http:
          port: 8080
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        hajimari.io/enable: "false"
  resources:
    requests:
      cpu: 5m
      memory: 10Mi
    limits:
      memory: 50Mi
