---
app-template:
  controller:
    strategy: RollingUpdate
  image:
    repository: ghcr.io/onedr0p/theme-park
    tag: 1.16.0@sha256:ea7df908833d0aa7b9b68dd74708d48ce4aef4e03b79ef32946e2188eecd6fc6
  service:
    main:
      ports:
        http:
          port: 8080
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        hajimari.io/enable: "false"
  resources:
    requests:
      cpu: 5m
      memory: 10Mi
    limits:
      memory: 50Mi
