app-template:
    ingress:
        main:
            hosts:
                - host: ENC[AES256_GCM,data:y5ReR62kkSN932vt83+5npo=,iv:LxNTgIyQNVuNEkh7PFGgk+DV0pfxc91fT2B4jUQa+rg=,tag:kIsVb1V8IyUy7G6eZ/l5tA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:sg==,iv:cS/KdLrKxTjrkRU17nQU7yRFwaG+aAy/cwnqeiURPBw=,tag:PPLEPtndidSuaTg/6UTlYw==,type:str]
                      pathType: ENC[AES256_GCM,data:U7ttPhq5,iv:YqkvfLqQSbAe4hQikhEFxLTbJimgXmFtBY+nSnfZNjg=,tag:1GHNetjABZk8a8aOQLxM9Q==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:Y/9hy2btx8/mRa91AFjssuM=,iv:k7eD7pclMaq1OAzllSRFd+NpoyXvn7mree/uNJ5Ib64=,tag:O7CFM+fRWefOOu9Kt17ExA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNekJuVVk3Y2VGeng2N3ZV
            Q3gwQ3hxcTkzaGwvM3FDZCtZZmdkT29HTWkwCmRod1JlMHl5allvUjdHVDF4RXFn
            a0RwQ1VEdU1hZ1J2VWFTbTduTU1GUDQKLS0tIGk3MTV4N1JseFRYellvQTNOQkZ3
            ZnpqQ2hTRDdCL3dRTEtPb2NMUUx6V2cK1RUhuZK7KQ4YNPh7SBlzvfhVkygWd/S6
            Hd/pXkKxhX0xYmUa8uVbR0weZ6U99LhskKBvXoLCb1mqap9xXPkVkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-26T21:02:07Z"
    mac: ENC[AES256_GCM,data:t6mdDKMuNc9aZyq0fg5GDBdQOztFeXzc5dnopfLX978RC8bYmuR3EKAGyCH6Dgk0/Jz/zSdQy8jb0QhOKJLzjnqgeA34Cl3UplFy8LXilYV3Y2CJH5Glc0D+fWqrlBmPVsxWxUP8wpX3TqzdCaBbmWdLVo3HeJrZmRvRfwuOwW4=,iv:fiMHWXhrMXeQUglE9f8D2ywCgwzKC5CO+cpJVL/ODao=,tag:vBtiFqMUR8f69rxME24E/g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
