---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mullvad
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mullvad
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        # WIREGUARD_PRIVATE_KEY WIREGUARD_ADDRESSES
        key: Mullvad
