---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: qbittorrent
spec:
  headers:
    customResponseHeaders:
      x-webkit-csp: ""
      content-security-policy: ""
      X-Frame-Options: ""
      Accept-Encoding: ""

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: theme
spec:
  plugin:
    theme-park:
      baseUrl: "https://theme-park.{{ .Values.custom.domain }}"
      app: qbittorrent
      theme: dracula
