---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: sonoff-zigbee-key
spec:
  rules:
    - # Sonoff Zigbee 3
      name: sonoff.zigbee
      labels:
        sonoff.feature.node.kubernetes.io/zigbee: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            class: { op: In, value: ["02"] }
            vendor: { op: In, value: ["10c4"] }
            device: { op: In, value: ["ea60"] }
