---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zigbee2mqtt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        TZ: Europe/Berlin
        ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
        ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
        ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: "false"
        ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_TRIGGERS: "false"
        ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
        ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
        ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
        ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "false"
        ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: warn
        ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
        ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: "{{ `{{ .NETWORK_KEY }}` }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: "{{ `{{ .PAN_ID }}` }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: "{{ `{{ .EXT_PAN_ID }}` }}"
        ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: "60"
        ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: "2000"
        ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
        ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
        ZIGBEE2MQTT_CONFIG_DEVICES: devices.yaml
        ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: "8080"
        ZIGBEE2MQTT_CONFIG_FRONTEND_URL: "{{ `{{ .url }}` }}"
        ZIGBEE2MQTT_CONFIG_GROUPS: groups.yaml
        ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: zigbee2mqtt
        ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
        ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: "60"
        ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "{{ `{{ .mqtt_password }}` }}"
        ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "true"
        ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://emqx.home
        ZIGBEE2MQTT_CONFIG_MQTT_USER: zigbee2mqtt
        ZIGBEE2MQTT_CONFIG_MQTT_VERSION: "5"
        ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
        ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_28f99eb10f86ec11903e631719c2d21c-if00-port0
        ZIGBEE2MQTT_DATA: /data
  dataFrom:
    - extract:
        key: Zigbee2mqtt
        conversionStrategy: Default
        decodingStrategy: None
