---
app-template:
  image:
    repository: rssbridge/rss-bridge
    pullPolicy: IfNotPresent
    tag: sha-a1b6bca
  strategy:
    type: Recreate

  env:
    TZ: Europe/Berlin
    PUID: "1000"
    PGID: "1000"

  service:
    main:
      ports:
        http:
          port: 80
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "rss-box"
        hajimari.io/group: "RSS Bridge"
  persistence:
    config:
      enabled: true
      mountPath: /config
      existingClaim: rss-bridge-config
      retain: true
  resources:
    limits:
      memory: 513Mi

  addons:
    codeserver:
      enabled: true
      image:
        repository: ghcr.io/coder/code-server
        tag: 4.12.0
      env:
        TZ: Europe/Berlin
      workingDir: /config
      args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          hajimari.io/appName: "RSS Bridge Config"
          hajimari.io/icon: cib:visual-studio-code
          hajimari.io/enable: "true"
          hajimari.io/info: VS Code for RSS Bridge configuration editing
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: networking-authelia@kubernetescrd
      volumeMounts:
        - name: config
          mountPath: /config
