grafana:
    ingress:
        hosts:
            - ENC[AES256_GCM,data:BfmltFf7/Gt3L+NZCclI2zwa,iv:o4D7lmhjSeebW3piouY5JoBla+RSeG3l3oXAbyJ5ZrM=,tag:IHomU24EbrS2Am6EYSByGQ==,type:str]
        tls:
            - hosts:
                - ENC[AES256_GCM,data:fzT3pKZydqC9ThUsW2/uiRUA,iv:WFt+qi/sPqt1RGiwVONAOKoQ3ogK0iRO272AoahaWAA=,tag:huz5oc7CsNkAUtOH1JOeSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQys4bzdUcnlUSWFWRVMy
            NWVGR3JlbTRxWWI5OXNTeXlHRktldW1GK1dZCmRWSnBSSWFCNHcrRlV0WlhpLzdB
            a1lUY3ovcHdhTC9YbW93TDJaeHNYdWMKLS0tICtybEthVVFnNUQvYjd4THpxbUpV
            THZGQTdhOElXK3hlM3FDbGZqRVZKK2MKEc8LgRo9Rep40TGOKMxYGuOsZdje1iVR
            zEEuiY9BybVUeycP6FVyxgACmsaDW2aXQLTtrlfDEUvkrI+e6Ict4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-20T20:50:29Z"
    mac: ENC[AES256_GCM,data:B9+Se64j6yF2lHW/9XBRLY+pZ2QRDp6C2euIFnDzN6lw2VUXqygRWrsStL3l5jUGA9Avbyfo6XpZgoJ1J1jLrqom8ZOe25H7av1bKYkpZ6ktJg6dtvw8TpUE1o8j11OobWKP9pIGpgO70/bwxXnAiukv41IdxKRDWVcWoqziH6g=,iv:LX/CQcIQipOMFMzwkcP0Rn69F8D5dRql3NzZoyWJruk=,tag:1TDgpfV5n0MO2/ljLwH1Vg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
