grafana:
    hostAliases:
        - ip: ENC[AES256_GCM,data:ktlYlB1lsVFKBFuz,iv:EJmRJKXhf7hwxfRTWXhPRb7Xa2Pm2CJGc/4rkAIKFV0=,tag:Wh1v2bZ2B5igUQHwS6DpgA==,type:str]
          hostnames:
            - ENC[AES256_GCM,data:tZB/GYfZdYP0+7TK4+ZS,iv:7a2XfOGnf2z4oe1SDBL043xuuo9WfXXxeVNZAyuUPnE=,tag:J6GDQOq0q1Bq5xSZv9AviQ==,type:str]
    ingress:
        hosts:
            - ENC[AES256_GCM,data:BfmltFf7/Gt3L+NZCclI2zwa,iv:o4D7lmhjSeebW3piouY5JoBla+RSeG3l3oXAbyJ5ZrM=,tag:IHomU24EbrS2Am6EYSByGQ==,type:str]
        tls:
            - hosts:
                - ENC[AES256_GCM,data:fzT3pKZydqC9ThUsW2/uiRUA,iv:WFt+qi/sPqt1RGiwVONAOKoQ3ogK0iRO272AoahaWAA=,tag:huz5oc7CsNkAUtOH1JOeSA==,type:str]
    env:
        GF_SERVER_ROOT_URL: ENC[AES256_GCM,data:ssGxsgMV8hQwghUBsYnFy9SEM0Few3WnLoQ=,iv:ZlFhw5rGtYcYHqLWij1f5xVFtOSuonhqESGvR2/svpg=,tag:JDNK3zRDAlmnPYG8eFsRUg==,type:str]
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: ENC[AES256_GCM,data:5CkuGBNwYL+9KQSqe+NUHEpGoVCGseMhP/GihSmTgioVpAMssGG/OIrq5NIOCQ==,iv:J76ExenAoffZelp11oXTUC/tbH/k7vrmTae8wWhwwn4=,tag:StpSULCgUU8d0861CMjTDg==,type:str]
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:tGxW32urYGsm6kaASK0Pruu7Fjz1x5AwobTHKhiJ/g1izSJN2sE=,iv:X5IzaE5bz98kgkJm9+eBKiVaWwW/wuP9GqYDhH1AoTY=,tag:gmaQkNhwyHvpBA7oUdpRdA==,type:str]
        GF_AUTH_GENERIC_OAUTH_API_URL: ENC[AES256_GCM,data:m/3cOC3KpkhRURCMiUx1o7RQcaC99QJ/ZgWrr2s9uYLI+8rkWr8L7B8=,iv:ZDgKFDd0rioRqcLp/G41W2/wnswaTnenDwh87PujAGI=,tag:6KtBMuqyQqVH5Plt65Y3Yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQys4bzdUcnlUSWFWRVMy
            NWVGR3JlbTRxWWI5OXNTeXlHRktldW1GK1dZCmRWSnBSSWFCNHcrRlV0WlhpLzdB
            a1lUY3ovcHdhTC9YbW93TDJaeHNYdWMKLS0tICtybEthVVFnNUQvYjd4THpxbUpV
            THZGQTdhOElXK3hlM3FDbGZqRVZKK2MKEc8LgRo9Rep40TGOKMxYGuOsZdje1iVR
            zEEuiY9BybVUeycP6FVyxgACmsaDW2aXQLTtrlfDEUvkrI+e6Ict4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-20T21:23:19Z"
    mac: ENC[AES256_GCM,data:R+3W0T38iAEwprHgrGqpG96LZF3WAA3zrI2pdjyOy26HWlxmgBlPavVhmdA28EcrghA4vgPzDDCuNIqrFR3I+l7a38LFvwLQkupxaajmH98ay7B1lR03vlpgYLuH8sYFZOy9hdwLNj/y+EMQyLZNKMKPhBp0J6I4mZokAzBkpYc=,iv:pb4/pv4I55xOE0HCWE7tJ2ZMbfOkkkL7jtTr0uc7kj8=,tag:q/gCN27eqC8Vjtf/mgUSzw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
