---
app-template:
  controller:
    type: cronjob
    cronjob:
      schedule: "@daily"
      ttlSecondsAfterFinished: 86400
  restartPolicy: OnFailure
  image:
    repository: ghcr.io/recyclarr/recyclarr
    tag: edge@sha256:08a4097196667ad265e9a30280f87f747adfe774ee3da706c105eb4513209e67
  command: ["/app/recyclarr/recyclarr"]
  args: ["sync"]
  envFrom:
    - secretRef:
        name: recyclarr
  service:
    main:
      enabled: false
  persistence:
    config:
      enabled: true
      type: secret
      name: recyclarr
      subPath: recyclarr.yml
      mountPath: /config/recyclarr.yml
      defaultMode: 0775
      readOnly: true
