---
app-template:
  controller:
    type: cronjob
    cronjob:
      schedule: "@daily"
      ttlSecondsAfterFinished: 86400
  restartPolicy: OnFailure
  image:
    repository: ghcr.io/recyclarr/recyclarr
    tag: edge@sha256:f126b9740f546a57517e0c60494861633b40fa346cde17bbd90aeb99d4547d00
  command: ["/app/recyclarr/recyclarr"]
  args: ["sync"]
  envFrom:
    - secretRef:
        name: recyclarr
  service:
    main:
      enabled: false
  persistence:
    config:
      enabled: true
      type: secret
      name: recyclarr
      subPath: recyclarr.yml
      mountPath: /config/recyclarr.yml
      defaultMode: 0775
      readOnly: true
