---
app-template:
  controller:
    type: cronjob
    cronjob:
      schedule: "@daily"
      ttlSecondsAfterFinished: 86400
  restartPolicy: OnFailure
  image:
    repository: ghcr.io/recyclarr/recyclarr
    tag: edge@sha256:d6fc020b4910f8d8526c9b0224f1c6e07e30feca35aa70fbbba523104ad374bc
  command: ["/app/recyclarr/recyclarr"]
  args: ["sync"]
  envFrom:
    - secretRef:
        name: recyclarr
  service:
    main:
      enabled: false
  persistence:
    config:
      enabled: true
      type: secret
      name: recyclarr
      subPath: recyclarr.yml
      mountPath: /config/recyclarr.yml
      defaultMode: 0775
      readOnly: true
