---
app-template:
  controller:
    type: cronjob
    cronjob:
      schedule: "@daily"
      ttlSecondsAfterFinished: 86400
  restartPolicy: OnFailure
  image:
    repository: ghcr.io/recyclarr/recyclarr
    tag: edge@sha256:e4b98fc0a14a2ac4bc5d7e2fd8bb47ad6ab0fb7b840deca3ba99656b68107dd8
  command: ["/app/recyclarr/recyclarr"]
  args: ["sync"]
  envFrom:
    - secretRef:
        name: recyclarr
  service:
    main:
      enabled: false
  persistence:
    config:
      enabled: true
      type: secret
      name: recyclarr
      subPath: recyclarr.yml
      mountPath: /config/recyclarr.yml
      defaultMode: 0775
      readOnly: true
