---
app-template:
  controller:
    type: cronjob
    cronjob:
      schedule: "@daily"
      ttlSecondsAfterFinished: 86400
  restartPolicy: OnFailure
  image:
    repository: ghcr.io/recyclarr/recyclarr
    tag: edge@sha256:25a13100cb905b8e21d81f2a4a3959812a7b1df67a04f7c26fcba87e95097d4d
  command: ["/app/recyclarr/recyclarr"]
  args: ["sync"]
  envFrom:
    - secretRef:
        name: recyclarr
  service:
    main:
      enabled: false
  persistence:
    config:
      enabled: true
      type: secret
      name: recyclarr
      subPath: recyclarr.yml
      mountPath: /config/recyclarr.yml
      defaultMode: 0775
      readOnly: true
