---
app-template:
  image:
    repository: "ghcr.io/clempat/tatort-telegram-bot"
    tag: main
  nodeSelector:
    "kubernetes.io/arch": "amd64"
  controller:
    type: statefulset
    annotations:
      reloader.stakater.com/auto: "true"
  service:
    main:
      enabled: false
  envFrom:
    - secretRef:
        name: tatort-bot-secrets
