---
app-template:
  controller:
    annotations:
      reloader.stakater.com/auto: "true"
  image:
    repository: ghcr.io/yoryan/mailrise
    tag: 1.4.0

  service:
    main:
      ports:
        http:
          enabled: false
        smtp:
          enabled: true
          primary: true
          port: 25
          protocol: TCP

  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        nginx.ingress.kubernetes.io/whitelist-source-range: |
          10.0.0.0/8,172.16.0.0/12,192.168.0.0/16

  persistence:
    notifier:
      enabled: true
      type: secret
      name: mailrise-config
      subPath: mailrise.conf
      mountPath: /etc/mailrise.conf
      readOnly: true

  resources:
    requests:
      cpu: 20m
      memory: 50m
    limits:
      memory: 100M
