---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpoller
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unpoller-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        UP_UNIFI_DEFAULT_URL: "https://192.168.10.1"
        UP_UNIFI_DEFAULT_USER: "{{ `{{ .UNPOLLER_USERNAME }}` }}"
        UP_UNIFI_DEFAULT_PASS: "{{ `{{ .UNPOLLER_PASSWORD }}` }}"
  dataFrom:
    - extract:
        key: Unifi
        conversionStrategy: Default
        decodingStrategy: None
