---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: prowlarr
spec:
  plugin:
    theme-park:
      app: prowlarr
      theme: dracula
      baseUrl: "{{ .Values.baseUrl }}"
