---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: prowlarr-middleware
spec:
  plugin:
    themepark:
      app: prowlarr
      theme: dracula
      baseUrl: "{{ .Values.baseUrl }}"
