apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name "{{ .Values.homelab_domain }}-tls"
spec:
  dnsNames:
    - "{{ .Values.homelab_domain }}"
    - "*.{{ .Values.homelab_domain }}"
  secretName: *name
  issuerRef:
    name: letsencrypt-prodution
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
