---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: clement.patout@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: clement.patout@gmail.com
            apiKeySecretRef:
              name: cloudflare-secret
              key: ORIGIN_API_KEY
        selector:
          dnsZones:
            - {{ .Values.homelab_domain }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: clement.patout@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: clement.patout@gmail.com
            apiKeySecretRef:
              name: cloudflare-secret
              key: ORIGIN_API_KEY
        selector:
          dnsZones:
            - {{ .Values.homelab_domain }}
