---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: Cloudflare
        property: GLOBAL_API_KEY
