---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
    namespace: external-secrets
  target:
    name: cloudflare-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: Cloudflare
        property: ORIGIN_API_KEY
