app-template:
    env:
        N8N_EDITOR_BASE_URL: ENC[AES256_GCM,data:LsN9akwwqfld9UKN2oYAj8L8+obwKElEY5pgcgKPYF/Hegy1n3s=,iv:4iHQDkEmZtuUS4AJooMlxzxcUslpgX9pdivCzbdKVEA=,tag:zUwiY8LLiI8v1bkBTkJSrA==,type:str]
        N8N_HOST: ENC[AES256_GCM,data:GkHjbVGu1CSCoumfoH0rKfJbn56+pISln3RBYA8N,iv:/wvru3ZX++QcElffjBL7v2wbVwr4E3TjR0yvAtHwALM=,tag:GHcqdPJXQeckvBCrR3V8Vg==,type:str]
    ingress:
        main:
            annotations:
                external-dns.alpha.kubernetes.io/target: ENC[AES256_GCM,data:ZiHxBGqwP/ZveQiAXYiD,iv:e2I1m1aK8G6gaCPq4jBokjofJ4gAGRo2VnQ+WwAdSVk=,tag:XgGuJkUGBZaL4n+VlUhfVQ==,type:str]
            hosts:
                - host: ENC[AES256_GCM,data:751iB8jbKoa7neRL3U4WQEAOrpKOpvdzy9xMMLP6,iv:IlnH4nwoFS2qx0xFkXNAk1N49KCNPPEDAIu9o+Q8tMc=,tag:OecOqM9N2yJmO+Xta0ATpA==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:RA==,iv:YAg28eyVUf+Lx5wGu/zEiI3xYzGB839+EieFmvWe4Gk=,tag:/8tAhk4FcL2S3IHP4NxNYQ==,type:str]
                      pathType: ENC[AES256_GCM,data:f2CwJp/k,iv:V9m5HR4wejAYWaPrFCv/5aQip+i22kBztFWnvyFkgqI=,tag:IGk/QyZDt9voaDfFL6yAfg==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:e22E0SsCqribDCTkBB8QPyERX4vPYnz32Utf4PjK,iv:GBHsnJxgPRtips4yjWZrS3WU7WmtlR18Zj2E2QDhMiU=,tag:SHo282KrFqLcZ0/NRcmRMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydXJOaDg5RDJGVytxZHJJ
            S3c4VXhYeDhMVCt2STJJeGpjWVhoci9OVVIwCkxKMVZUV000eGtMcFplR2tDaDdy
            dThFVjBkSldHTzQxSlowSlhGcGs1VTAKLS0tICtIR3hOTmt4cVJJOWhtMnR5NllG
            YXNEU1RpRVZ5Zm51VEZqMDZMY29aY2cKpq1WUYGyVCShImODX8QDWq6dGGCDpwiE
            33QzylvC65jj41U2YVCk8qg+QX3yDCeJ4vZnn7N8PcRxBqiXEsbapQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T19:52:23Z"
    mac: ENC[AES256_GCM,data:rzG9S5M3Odf5rlCnAt9oyEoapeF8srmm0N/WiXviw3DJlqCKtUwOQOasEj7rBeAJJrf9oOX0J4vLUJ1taDnei85tw1QzUWCeIFI4EZU1jICUFBL19d5ReqHjBsCfA8iHDhQH4wHc49H+riuLG0TBroQOt9EhFEG+1S+UFTPEfEE=,iv:yHxbSVCTBjsmZAU469sMnrhF1kJrJR6Mu71A1FkoNjU=,tag:/n5L5GVFWRhy6rYnHy4oRQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
