---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: esphome-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secrets.yaml: |-
          wifi_ssid: "{{ `{{ .esphome_wifi_ssid }}` }}"
          wifi_pwd: "{{ `{{ .esphome_wifi_password }}` }}"
          wifi_fallback_ssid_password: "{{ `{{.esphome_wifi_fallback_ssid_password }}` }}"
          mqtt_host: "{{ `{{ .emqx_host }}` }}"
          mqtt_user: "{{ `{{ .emqx_esp_username }}` }}"
          mqtt_pwd: "{{ `{{ .emqx_esp_password }}` }}"
          domain_devices: not.local
  dataFrom:
    - extract:
        key: Esphome
        conversionStrategy: Default
        decodingStrategy: None
      rewrite:
        - regexp:
            source: "(.*)"
            target: "esphome_$1"
    - extract:
        key: EMQX
        conversionStrategy: Default
        decodingStrategy: None
      rewrite:
        - regexp:
            source: "(.*)"
            target: "emqx_$1"
