---
app-template:
  image:
    repository: freshrss/freshrss
    pullPolicy: IfNotPresent
    tag: 1.21.0
  strategy:
    type: Recreate
  nodeSelector:
    "kubernetes.io/arch": "amd64"

  initContainers:
    init-db:
      image: ghcr.io/onedr0p/postgres-initdb:14.8
      imagePullPolicy: IfNotPresent
      envFrom:
        - secretRef:
            name: freshrss-secret

  env:
    TZ: Europe/Berlin
    CRON_MIN: "18,48"
    PUID: "1000"
    PGID: "1000"

  envFrom:
    - secretRef:
        name: freshrss-secret

  service:
    main:
      ports:
        http:
          port: 80
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "rss-box"
        hajimari.io/group: "News"
  persistence:
    config:
      enabled: true
      mountPath: /var/www/FreshRSS/data
      existingClaim: freshrss-config
      retain: true
  resources:
    limits:
      memory: 513Mi
