---
kind: Service
apiVersion: v1
metadata:
  name: truenas
spec:
  type: ExternalName
  ports:
    - port: 80
      name: web
    - port: 9001
      name: minioe
    - port: 9003
      name: s3
  externalName: 192.168.30.4

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: truenas
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: &host nas.{{ .Values.custom.domain }}
      http:
        paths:
          - backend:
              service:
                name: truenas
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - *host
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
spec:
  endpoints:
    - path: /minio/v2/metrics/cluster
      port: s3
      scheme: http
  selector:
    matchLabels:
      external: minio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minioe
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hajimari.io/enable: "true"
    hajimari.io/icon: bucket
    hajimari.io/appName: MinIO
    hajimari.io/info: MinIO offers high-performance, S3 compatible object storage
spec:
  ingressClassName: traefik
  rules:
    - host: &host minioe.{{ .Values.custom.domain }}
      http:
        paths:
          - backend:
              service:
                name: truenas
                port:
                  name: minioe
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - *host
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s3
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: &host s3.{{ .Values.custom.domain }}
      http:
        paths:
          - backend:
              service:
                name: truenas
                port:
                  name: s3
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - *host
