---
kind: Service
apiVersion: v1
metadata:
  name: nextcloud
spec:
  type: ExternalName
  ports:
    - port: 9000
      name: http
  externalName: 192.168.30.4

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: &host cloud.{{ .Values.custom.domain }}
      http:
        paths:
          - backend:
              service:
                name: nextcloud
                port:
                  number: 9000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - *host
