---
app-template:
  controller:
    type: statefulset

  image:
    repository: ghcr.io/esphome/esphome
    tag: 2023.8.2

  podAnnotations:
    secret.reloader.stakater.com/reload: esphome-secrets

  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  service:
    main:
      ports:
        http:
          port: 6052

  ingress:
    main:
      enabled: true
      ingressClassName: traefik

  persistence:
    secrets:
      enabled: true
      type: secret
      name: esphome-secrets
      mountPath: /config/secrets.yaml
      subPath: secrets.yaml
    esphome-cache:
      enabled: true
      type: emptyDir
      mountPath: /config/.esphome

  resources:
    requests:
      cpu: 300m
      memory: 512M
    limits:
      memory: 2048M

  volumeClaimTemplates:
    - name: config
      mountPath: /config
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: longhorn

  addons:
    codeserver:
      enabled: true
      image:
        repository: ghcr.io/coder/code-server
        tag: 4.16.1
      env:
        TZ: Europe/Berlin
      workingDir: /config
      args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          hajimari.io/appName: "Esphome Config"
          hajimari.io/icon: cib:visual-studio-code
          hajimari.io/enable: "true"
          hajimari.io/info: VS Code for Esphome configuration editing
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: networking-authelia@kubernetescrd
      volumeMounts:
        - name: config
          mountPath: /config
