---
app-template:
  controller:
    type: statefulset
    replicas: 1
    annotations:
      reloader.stakater.com/auto: "true"
  image:
    repository: vabene1111/recipes
    tag: 1.5.6
    pullPolicy: IfNotPresent
  strategy:
    type: Recreate
  env:
    TZ: "Europe/Berlin"
    ALLOWED_HOSTS: "*"
    REVERSE_PROXY_AUTH: 1
    SOCIAL_PROVIDERS: allauth.socialaccount.providers.openid_connect
  envFrom:
    - secretRef:
        name: recipes-secret

  initContainers:
    init-db:
      image: ghcr.io/onedr0p/postgres-initdb:14.8
      imagePullPolicy: IfNotPresent
      envFrom:
        - secretRef:
            name: recipes-secret
  service:
    main:
      ports:
        http:
          port: 8080

  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hajimari.io/enable: "true"
        hajimari.io/icon: game-icons:meal
        hajimari.io/appName: Cookbook
        hajimari.io/info: Meal recipes

  volumeClaimTemplates:
    - name: media
      mountPath: /opt/recipes/mediafiles
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: longhorn

    - name: static
      mountPath: /opt/recipes/staticfiles
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: longhorn

  resources:
    limits:
      memory: 3000Mi
    requests:
      cpu: 100m
      memory: 1000Mi
