---
app-template:
  controller:
    type: statefulset
    annotations:
      reloader.stakater.com/auto: "true"
  image:
    repository: qmcgaw/ddns-updater
    tag: latest
  env:
    PUBLICIP_HTTP_PROVIDERS: ifconfig

  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: networking-authelia@kubernetescrd
  service:
    main:
      ports:
        http:
          port: 8000
  securityContext:
    runAsUser: 1000
  persistence:
    config:
      enabled: true
      type: secret
      name: ddns-updater-config
      subPath: config.json
      mountPath: /updater/data/config.json
      defaultMode: 421
      readOnly: true
