---
app-template:
  controller:
    type: statefulset
    annotations:
      reloader.stakater.com/auto: "true"
  image:
    repository: qmcgaw/ddns-updater
    tag: latest
  env:
    PUBLICIP_HTTP_PROVIDERS: ifconfig
    DATADIR: /data
    TZ: Europe/Berlin
    BACKUP_DIRECTORY: /backups

  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: networking-authelia@kubernetescrd
  service:
    main:
      ports:
        http:
          port: 8000
  securityContext:
    runAsUser: 1000
  volumeClaimTemplates:
    - name: data
      mountPath: /data
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: longhorn
  persistence:
    config:
      enabled: true
      type: secret
      name: ddns-updater-config
      subPath: config.json
      mountPath: /data/config.json
      defaultMode: 0755
      readOnly: true
