---
app-template:
  controller:
    type: statefulset
    replicas: 1
    annotations:
      reloader.stakater.com/auto: "true"
  image:
    repository: ghcr.io/koenkk/zigbee2mqtt
    tag: 1.37.0
  tolerations:
    - key: "hardware"
      operator: "Equal"
      value: "rpi"
      effect: "NoExecute"
  envFrom:
    - secretRef:
        name: zigbee2mqtt-secret
  service:
    main:
      ports:
        http:
          port: 8080
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: networking-authelia@kubernetescrd
        hajimari.io/enable: "true"
        hajimari.io/icon: zigbee
        hajimari.io/appName: Zigbee2MQTT
        hajimari.io/info: Zigbee to MQTT bridge
  securityContext:
    privileged: true
  nodeSelector:
    feature.node.kubernetes.io/usb-ff_10c4_ea60.present: "true"
  persistence:
    config:
      enabled: true
      existingClaim: zigbee2mqtt
      mountPath: "/data"
    usb:
      enabled: true
      type: hostPath
      hostPath: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_28f99eb10f86ec11903e631719c2d21c-if00-port0
      hostPathType: CharDevice
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 500Mi
