emqx:
    emqxConfig:
        EMQX_DASHBOARD__DEFAULT_PASSWORD: ENC[AES256_GCM,data:qizvksJsDJpvRH9ysoIhPw==,iv:oLevu337UtPzmHN9riyPiQgUZ1Pfn8IF3AQFtagXwYw=,tag:fBI8iSlO3Pwyx/FOyv3Xyw==,type:str]
        EMQX_AUTH__USER__1__USERNAME: ENC[AES256_GCM,data:QPNjIw==,iv:xX8VWTNFREOA8iX/VZ6xKcXwXG0P2UkgVTOJo3EJTa8=,tag:uJIx98AiPPcakZQXNHLnIw==,type:str]
        EMQX_AUTH__USER__1__PASSWORD: ENC[AES256_GCM,data:5FnxOBkv7JiRayWkJateDw==,iv:EsQbY/uX3cPyNplGW4YJWSPNGNjePqvfLEX3a9vwjpY=,tag:M2MSk+xvQJxSAE4SrXZBnA==,type:str]
    ingress:
        dashboard:
            enabled: ENC[AES256_GCM,data:TRXSUA==,iv:ST6g2B8wzl9jFZG6jFNh+6Z43SnxfB7qrwg4XMPcXXQ=,tag:UIMYfnJMl5Mbf6McpkiLpw==,type:bool]
            ingressClassName: ENC[AES256_GCM,data:nYor1o9zFQ==,iv:j2PgAPksZw/1dp5Qphi0KLqczHYjmfPrRGSbnhvcCkY=,tag:OuQg9CkHXkLFTsWlk9kkgw==,type:str]
            annotations:
                nginx.ingress.kubernetes.io/whitelist-source-range: ENC[AES256_GCM,data:+fKw7k4e7ksSJoHzTsXteoNnKZ+E75PadHldq91nYYPyOkFVOCOMkw==,iv:Rj2TOI71iPGOhvK9m9SkvD23I2bLWknVu/sjSagq5vE=,tag:nZzbJjNokw6Lc2Kg7dVBvw==,type:str]
                hajimari.io/appName: ENC[AES256_GCM,data:Lel2vw==,iv:l5GMRhAYv6yKEhVA56IqJ20dd7032W5gW7Z9D2iEQV8=,tag:EUzxEKPmz+jdWeHJw86E+g==,type:str]
                hajimari.io/icon: ENC[AES256_GCM,data:9S2S5X62hYUabPm5NxahjimRCvSV2BIlwwwtg+A=,iv:aEcGK/EgyB8S88uGYyjAspLdtkMu65A1wnGi1nfV9gY=,tag:c4RDYRBybk+kz9g1t5Potw==,type:str]
            path: ENC[AES256_GCM,data:7g==,iv:dexKMdGb13OZimQSwra3m3+/dA7kmE1rGa6ER6F+8i4=,tag:lxH7i8gRj7Sro9gchAoqqA==,type:str]
            pathType: ENC[AES256_GCM,data:VsmRGOlH,iv:70qm7k7QiU4Dgs9cXkz+XoeoxEjf+GRqLxt3m58/Nnk=,tag:sFGHx+IAAuVXMWotpJsvOg==,type:str]
            hosts:
                - ENC[AES256_GCM,data:SMAR+8xi0duhEcmb9I5r,iv:WCMkjs/up0rUhgvqt6zAL4fBXjwFcEzxSbC5qzAEjZQ=,tag:tnEr736B2lgtl8HJT52ILw==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:FsanU9ieFynepeAayJ0L,iv:sini2GSvO16ROMbkEdQZeXHrjNQduhHyosGQ2knUpjU=,tag:XE/lo6KHBUBtASYpavy+zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZENlQVVUV0lUZjBXWU1H
            NGdPYzFSZUo0dVRVcGpFUjI3aDZiOEY4M0hjCkJLWUUycGRaY2pYYjVpQURGdlBl
            Q1UwaCtqTkdKcXI1bmZyeVFnOUtaaXcKLS0tIHA2d3AxKzIxWHV3QWRFS0txMU9I
            NlpVOU9BMDVrRW9WTUtIY3dHSHlnVDgKSJM/XLjgfW17lN5+Y9chF/hyBIs3EvUI
            zOzsfSnvD+NOWqEdGDqkD9loFEj5GWXqcmqEPKD8v+S3nmkMVAjOxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-17T07:53:47Z"
    mac: ENC[AES256_GCM,data:bSzmemSebHMjHq9ox8+QFzgOUgt4pK5eksR3c/TQOBaBMR+kR8BWdCaw+51v+U5Cco78ZwKtKTyqvbjdVadF5Rkcosi3A7Ns4zS5r1wBKY8QufetFqJEg4B+wnEKW1lfMA8VSoNRRgolfLTJuq/vyDNgD8oK6G/pZg94oMVHF88=,iv:fc8+/+wUBdtyCuWSkTdX7XU+5f0k+IPwwj5RJGnrBcw=,tag:bsztpO4whVCKOd88gH/gHA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
