custom:
    homelab_domain: ENC[AES256_GCM,data:iOLmWUgHjHr5Qg==,iv:yFVwAZJvefHChJele4gVOuTgvuuBEom3uKZe2md5C3k=,tag:JnKLdJUPP/4GbKEll8bK7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcC9aVkxvekFuczVhdEJG
            dUk4a3ZLNWZ2cTUvTDdVdFo1YU5XbjRoL2hvCmdNMDV1Q0RWOEJwOTR0NEJCeTlU
            VXhJdTlHelRyVUVjZ0xpaFZOcmsrODAKLS0tIHJmZHNtWFlYcEErMmY5K0k0Q1dH
            RGMwZFg4c2RYa2x6THN3bUhib016MFkKkFobqzIRY6CZlSEF5K1kSmc1aF46R0+T
            4oG0sqx9z/1NjotHqoG+LsrnU+aS8S5TL+RRuS3t/PBNu6xXeg5HAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-25T07:28:27Z"
    mac: ENC[AES256_GCM,data:4A69UHiuh7zk892PLn7xEFdiFP54k10dJiGWLZYRvz39nYPY3BcHOEWuYcVX6/ZOAAW2C05PFLbvcBNogs18CRm0vQj3P3oSCawrxI1Jm+kZM/deZANhZ4iMrbeMEqWIv8v53x41/GgsAfmF0vV+H1bR+lB7V4+yE+P+PFV4CL8=,iv:pN5v0BeohKxGqDkyR7BDLu+MVmWteOP87CoIQkiAQkI=,tag:gdq0bOS9OFFssjH9xuSikA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
