app-template:
    ingress:
        main:
            hosts:
                - host: ENC[AES256_GCM,data:AouaODvnxMmSQmVd0QzDPG4=,iv:QEWMYr3Eg4xQelHv+jM7RQRlDYxZ1AmEkDaBBuugmdo=,tag:q/X/GUH+NL3UbT836cG+Cw==,type:str]
                  paths:
                    - path: ENC[AES256_GCM,data:Lg==,iv:+VY12AWs4RSEzX9zXSHW08uEx6WGb/qja6qrOnuZlJo=,tag:63z739WxQuIlfmUWMu9Pjw==,type:str]
                      pathType: ENC[AES256_GCM,data:kQFn/JVC,iv:dNYK1KhBMug45OWKLB/obd8/uWc5+59IQfaaO852T/8=,tag:uJPhDL+pIXY2LfgLaeIuLw==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:iAL0jk0CA2lJ/KFpmKfuIHY=,iv:8n4eE0ZhdousA+6tW5E6EhwhMMOqsrJemANf94l1I2Q=,tag:8Y2DvNdAEEBy7qedHL+44A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVGhiWmxuSHNvUXJsN0Js
            bDF2UkoyZ1l1d3pRMmtUd3F2R3ZhUWk4N2prCjhNN0F5bGdFR25CUUdpamticVVH
            QjFxb09RUm1EWklhZmo1NjhVWTBXY3MKLS0tIFh2RkJ5cGJNdTQ5eGlLVk84RGE0
            MTEreEpZN0owVGcrdEtySWlDV2gxakkKWT7xxRTcV3vccg0kCAlUq/pHEpiMCMpn
            BfkN13kxZ5258zJLSC0TqcwSAOqD/SEBBrBtZ1xTluTm8M7khsquBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-17T20:36:25Z"
    mac: ENC[AES256_GCM,data:jxOHoHX+m8H8L0924BVbVVADEFe5NplPkKo8KoVgG7CwYOc9o0KQyYIDzFWDM58t0iYE6CJ3AOcXYjw6eMTVd/J488KTUFLFjDWnuPKZlUiM7W5t75+6yMy3Lyz+yRf5WRg5K9QYnOth3hwxFPZ4UOKaSPtmr5u5kCtDQ0TQziw=,iv:cB4/DSKXYjW5vq37e4PF0xsSviSlaJtR+SCXfKb7PUA=,tag:aJ4sJz7ipTq1Pr24WZZNCA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
