---
node-feature-discovery:
  worker:
    tolerations:
      - effect: "NoExecute"
        operator: "Exists"
    config:
      core:
        sources: ["custom", "pci", "usb"]
      sources:
        usb:
          deviceClassWhitelist: ["02", "03", "0e", "ef", "fe", "ff"]
          deviceLabelFields: ["class", "vendor", "device"]
