---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: glauth
  namespace: authentication
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: glauth-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        server.toml: |
          debug = true
          [ldap]
              enabled = true
              listen = "0.0.0.0:389"
          [ldaps]
              enabled = false
          [api]
              enabled = true
              tls = false
              listen = "0.0.0.0:5555"
          [backend]
              datastore = "config"
              baseDN = "{{ "{{ .baseDN }}" }}"
        groups.toml: |
          [[groups]]
              name = "svcaccts"
              gidnumber = 6500
          [[groups]]
              name = "admin"
              gidnumber = 6501
          [[groups]]
              name = "people"
              gidnumber = 6502
        # Create passbcrypt:
        #   https://gchq.github.io/CyberChef/#recipe=Bcrypt(12)To_Hex('None',0)
        # or
        #   htpasswd -bnBC 10 "" YOUR_PASSWORD | tr -d ':\n' | od -A n -t x1 | sed 's/ *//g' | tr -d '\n'
        users.toml: |
          [[users]]
              name = "{{ "{{ .search_username }}" }}"
              uidnumber = 5000
              primarygroup = 6500
              passbcrypt = "{{ `{{.search_password}}` }}"
              [[users.capabilities]]
                  action = "search"
                  object = "*"
          [[users]]
              name = "{{ `{{.clempat_username}}` }}"
              mail = "{{ `{{.clempat_email}}` }}"
              givenname = "{{ `{{.clempat_givenname}}` }}"
              sn = "{{ `{{.clempat_surname}}` }}"
              uidnumber = 5001
              primarygroup = 6502
              othergroups = [ 6501 ]
              passbcrypt = "{{ `{{.clempat_password}}` }}"
          [[users]]
              name = "{{ `{{.melanie_username}}` }}"
              mail = "{{ `{{.melanie_email}}` }}"
              givenname = "{{ `{{.melanie_givenname}}` }}"
              sn = "{{ `{{.melanie_surname}}` }}"
              uidnumber = 5002
              primarygroup = 6502
              passbcrypt = "{{ `{{.melanie_password}}` }}"
  dataFrom:
    - extract:
        key: Glauth
        conversionStrategy: Default
        decodingStrategy: None
