---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        FRIGATE_MQTT_USERNAME: "frigate"
        FRIGATE_MQTT_PASSWORD: "{{ `{{ .MQTT_PASSWORD }}` }}"
        CAMERA_USER: "{{ `{{ .CAMERA_USER }}` }}"
        CAMERA_PASSWORD: "{{ `{{ .CAMERA_PASSWORD }}` }}"
  dataFrom:
    - extract:
        key: Frigate
        conversionStrategy: Default
        decodingStrategy: None
