---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          logger:
            default: info
            # logs:
            #   frigate.record: debug

          mqtt:
            host: emqx.home.svc.cluster.local
            topic_prefix: frigate
            user: "{FRIGATE_MQTT_USERNAME}"
            password: "{FRIGATE_MQTT_PASSWORD}"

          database:
            path: /data/frigate.db

          detectors:
            coral:
              type: edgetpu
              device: usb

          ffmpeg:
            global_args: ["-hide_banner", "-loglevel", "warning"]
            hwaccel_args: ["-hwaccel", "vaapi", "-hwaccel_device", "/dev/dri/renderD128", "-hwaccel_output_format", "yuv420p"]

          snapshots:
            enabled: true
            timestamp: false
            bounding_box: true
            retain:
              default: 2

          record:
            enabled: true
            retain:
              days: 2
              mode: all
            events:
              retain:
                default: 2
                mode: active_objects

          objects:
            track: ["person"]
            filters:
              person:
                threshold: 0.7


          go2rtc:
            streams:
              frigate_driveway_hq: "rtsp://{{ `{{ .CAMERA_USER }}` }}:{{ `{{ .CAMERA_PASSWORD }}` }}@192.168.31.10:554/h264Preview_01_main"
              frigate_driveway_lq: "rtsp://{{ `{{ .CAMERA_USER }}` }}:{{ `{{ .CAMERA_PASSWORD }}` }}@192.168.31.10:554/h264Preview_01_sub"
              frigate_stairs_hq: "rtsp://{{ `{{ .CAMERA_USER }}` }}:{{ `{{ .CAMERA_PASSWORD }}` }}@192.168.31.12:554/h264Preview_01_main"
              frigate_stairs_lq: "rtsp://{{ `{{ .CAMERA_USER }}` }}:{{ `{{ .CAMERA_PASSWORD }}` }}@192.168.31.12:554/h264Preview_01_sub"
              frigate_kitchen: "rtsp://rtsp:{{ `{{ .CAMERA_PASSWORD }}` }}@192.168.20.152:554/av_stream/ch0"
              # frigate_backyard_hq: 
              # frigate_backyard_lq: 
            webrtc:
              candidates:
                - 192.168.40.7:8555
                - frigate.frigate.svc.cluster.local:8555

          cameras:
            frigate_driveway:
              ffmpeg:
                output_args:
                  record: preset-record-generic-audio-copy
                inputs:
                  - path: rtsp://localhost:8554/frigate_driveway_hq?video=copy&audio=aac
                    input_args: preset-rtsp-restream
                    roles: ["record"]
                  - path: rtsp://localhost:8554/frigate_driveway_lq?video=copy
                    input_args: preset-rtsp-restream
                    roles: ["detect"]
              detect:
                width: 640
                height: 360
                fps: 10
              motion:
                mask:
                  - 1580,601,3052,601,3069,0,1498,0
              zones:
                gate:
                  coordinates: 1894,1058,2673,1058,2695,618,1872,596
                pathway:
                  coordinates: 3239,1585,3200,649,2595,627,2617,1071
            frigate_stairs:
              ffmpeg:
                output_args:
                  record: preset-record-generic-audio-copy
                inputs:
                  - path: rtsp://localhost:8554/frigate_stairs_hq?video=copy&audio=aac
                    input_args: preset-rtsp-restream
                    roles: ["record"]
                  - path: rtsp://localhost:8554/frigate_stairs_lq?video=copy
                    input_args: preset-rtsp-restream
                    roles: ["detect"]
              detect:
                width: 640
                height: 480
                fps: 10

            frigate_kitchen:
              ffmpeg:
                output_args:
                  record: preset-record-generic-audio-copy
                inputs:
                  - path: rtsp://localhost:8554/frigate_kitchen?video=copy&audio=aac
                    input_args: preset-rtsp-restream
                    roles: ["record"]
                  - path: rtsp://localhost:8554/frigate_kitchen?video=copy
                    input_args: preset-rtsp-restream
                    roles: ["detect"]
              detect:
                width: 1280
                height: 720
                fps: 5

        FRIGATE_MQTT_USERNAME: "frigate"
        FRIGATE_MQTT_PASSWORD: "{{ `{{ .MQTT_PASSWORD }}` }}"
  dataFrom:
    - extract:
        key: Frigate
        conversionStrategy: Default
        decodingStrategy: None
