kube-prometheus-stack:
    prometheus:
        ingress:
            hosts:
                - ENC[AES256_GCM,data:H1md6jmsNCdMkcgF+3xHB6zUBNxz,iv:Upji9JUeLcmi3DpG9HLkQSgcIRy86mkq6It8eYZ/eBg=,tag:dYZtBfQXci9eV0FZcfWF9A==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:KJAXNNaxD6y6YS34CPKjWxg7qSij,iv:Faghsc+EA8w/L10ryU8HwqhlS2lCABR2GvGsOqpb18Y=,tag:EXw1GMaPGdwl8utveHdvxw==,type:str]
    alertmanager:
        ingress:
            hosts:
                - ENC[AES256_GCM,data:wShEEDlnLq+DtTPHTzw2Y/rsQz8d4wg=,iv:g3FT4qqIHuIP9Hc479kpTFIO+chqmKD2HmlQ+/evSa0=,tag:x0VHQBrLQikOz4SFm1pdDg==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:eiulWNvDckQ+83xwCDxmYohoVaZJ29A=,iv:R7tW67IEqzMMuMU91HjLb20giOok5D0Uc8EkX03OaZM=,tag:dWBypoPHpRufoPgQnIyIaA==,type:str]
        config:
            receivers:
                - name: ENC[AES256_GCM,data:OdAnWBqYasqhMOezqa4=,iv:fgLTqggdYlWMh89xUNxFngQF4PIMvrDLdNg4siEvELI=,tag:rHJnhj0kjKzaNjjd6X1ieA==,type:str]
                  webhook_configs:
                    - url: ENC[AES256_GCM,data:MAH63YmHOCrMWO8PxVqyevQQu/w+SRnwOnLFBFQ7V4AkXJuApir0zFA4i8UW0bYERlkVxS2vTTo=,iv:X90DbBzpUhDZ9mwfRyTCtDuTdNv5TYExfwIbkwmgiqk=,tag:bJJfREPUya+t8mP4T63DQg==,type:str]
                      send_resolved: ENC[AES256_GCM,data:2L3/4Q==,iv:wt543sjclKsrnm/A699Q+T8+VGqauPOzg/lJPThQeRQ=,tag:9NRupkB7brF00Fc855fRUA==,type:bool]
                - name: ENC[AES256_GCM,data:khTMwQ==,iv:AAhUh1usBLXcK0SHD2OSoZG/lbJ6w5ji+qMEFVJ8hNA=,tag:ICwwd/p17Hi9bu7GBTNGiQ==,type:str]
                - name: ENC[AES256_GCM,data:Rv4FBmbX2Bc=,iv:5WcMZDUFGOKM9+v4dvERXm/YummGrqMJ58Qxh9qBA6U=,tag:9eoIMvQm6CkonzjyEKv44w==,type:str]
                  pushover_configs:
                    - token: ENC[AES256_GCM,data:Mey+Xb15yWH5MGVrHI/hQzlrZosMxakrYwul1lAH,iv:zr+vTL/CYybuofqx62O/Jpx6KBGKu7LzQfJ3N74aFjA=,tag:m1Zb2ZNC0pmlcnMPuvLvpQ==,type:str]
                      user_key: ENC[AES256_GCM,data:VKGaHqNdM4MfKREBMMn7sLZvJmOfMdllhnFA1bRr,iv:wdDLTth/Hz9uVwCeytNYmco/qUDXCjc6ZxHaalfpB38=,tag:iTkTMfNo8nrKN91QgW4fJQ==,type:str]
                      url_title: ENC[AES256_GCM,data:oDcNOUAtYC+ZUtU/CAwXQxWbwzM=,iv:c1r+jN/EL57c/NuoSndgv9/imlqvDlTuWfKwAu95F4o=,tag:sHpc5MctvQvV2Uqy8BQpsg==,type:str]
                      send_resolved: ENC[AES256_GCM,data:sjYoSA==,iv:JY4d1DCP+v23qibe7COMG1fYYnRvmRF9PtXyNL10M8o=,tag:YyjTzUv1tHOy/0l95okeZw==,type:bool]
                      html: ENC[AES256_GCM,data:Kloh6A==,iv:73iNvs84nbNuLAsXgGLNjZh3B30ZIIi/8RHUNPXOfC8=,tag:70hu05KoCHWlLN4GWPPOMA==,type:bool]
                      sound: ENC[AES256_GCM,data:5LInUT+gEw==,iv:eV4rZCF4OzBbzDfv67C7NRtk2CLBjhGn4WSoC3wIaY0=,tag:uMYaZDDr4uX0/cfcORRjVQ==,type:str]
                      priority: ENC[AES256_GCM,data:FeyfMKwXGkDktUvNWMrDXc+4Qbb+r0GwzK33TwQ73grQizENnrZ6bDugFR2+q/jiSg==,iv:2EOQin46m5rkgKiAcFfAxuh8f81L3XZdLzJmBOQgAds=,tag:4r2/s8f8qKFe6mS/AnCovQ==,type:str]
                      title: ENC[AES256_GCM,data:EWKkFKk44Q2ji8j/bcQ+kDTZ0nYP8wdgeEXqAQVQoTNWMqC94xee2+zgRGfSAnafOO3Jf5V3gl5FDKj6mogOTZ+Ec3meS6aTf5JGSU/8EidMtQlAL2umJfVeED9dFX0Aosulli3k1y752dh6jGXCiPHTO65ed74=,iv:64EULTBr1QrTCqT7vLLXgic+iEashLgKT3IPERnhZYE=,tag:yXstkuGote9KlUIdT/HClw==,type:str]
                      message: ENC[AES256_GCM,data:a2Pq6XXp5L7PmsG5szcBAZglj8xlqXkB9dUdUtcn4/J+Ps1zXazTzZ3GDrKNpCZTwSgtyAOLAi++hl+GOuxlUe+Dho0asmwcnrNWDhrdL5WATDNrSVKvrN9xYi14Yz7donRqcJKJFpoFuZt+HqULqXd64325QvDse4nuWNd1nZPuNTgxSGTcnEzu2VKkSZ6/ZtM4QAOWcWrfpW67uB4sU6s7ftO8XfhEjh0yfYcgcYS/9HO2pie7sSeqjlJy4aCsw8DBT9sNt/UndxgQNy0Ahpbqju7PW+MTYB6uZp/g13LN5y0dha7MlDbDjhQ/Qy9i7MlmnMfvlQrP8fWrc5+Vb+baHkxRkR3Ca8Os/H4nHLvnkKeOiSGUDEDpb8XEa35qW2Uvhm0CkwqMdleJIoDOKMILEtqo71d3rj+SjfXbpE2l8BTMjI7DU/9W173u1GgfGKMkAYJkJZJL4gIxkaUPXow7qaQxU+NGagmBmvkIsOoZvMc5p2rJP8Bv/TyUAAWnqKTcKAKgzX1WgRkkyI1JqD9nYPuMVs2GsK3TT9kZvkCTKdiCRDB6anfyb+4tS5jkOnzR4R/wCuObq+St7xbQbyIRWrXdAP1Gvo9bQAu3H7ka6yn8q1nvnmt+P6VqLd3iX0I6bF6tEvvPiscgyca56yK2jf3WIyWYVkOmkz83VepD+6pHCLGs28UbmrC/wkvG997e5wedx/uVDpo233+aWq7cfyHOE1wS6MY5zGbh78SkGr2kIxXnK1ig7TiwrIaTjquOgWSuiXet6Nk=,iv:BAe2LgBiMTNq6JDPp6BhIugbu18xx37HsNeGKTH8ol4=,tag:ZpHdFZWYov0sWcIzpe0bCw==,type:str]
    kubeControllerManager:
        endpoints:
            - ENC[AES256_GCM,data:uIFhAfc3bYBBuoRq+A==,iv:M+dUNHIVOITZZNEYDUkULANgLYHmXNXkAG+tGOh0XG0=,tag:rpnsT1D1dLZptgRR67BwCQ==,type:str]
    kubeScheduler:
        endpoints:
            - ENC[AES256_GCM,data:PyxsmRhXkQM8qHlvDw==,iv:JuKhiRyVk9y7ogK7ji3WKRCGRC31tSQIUT1tl+fL92c=,tag:NyNWUzNJhlItj3jdwKQ0qg==,type:str]
    kubeProxy:
        endpoints:
            - ENC[AES256_GCM,data:L9mjSs45lq0/mDytvQ==,iv:dDGoEIrYB+pGIAwH6mv/jra375x8INdzKop4aR899yI=,tag:ndiYuMGRieGzAr2WowgKtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJR2htMWlQZXNWNVE4emM5
            VTkxUnBVbWx4SUp3VjN0c2FIdnJTSzJ2Z204CmZPRGYwL1h3ZE1QVE5LaUZ3eE1M
            NVMzRXhCYVQwck83WGZzb0N5bElzSEkKLS0tIFIxcnBvL1RvdUIwWHQwUTRadnRF
            cEVCTTB6b1pSYit0elMyRFZ2RlhjSkUKXtoWVoe1cUoL5CsVzbF6lgp23aO8ixtj
            +9WH+V1DeAiWDe9JgdmJMm3GlJoh0UaLpEFOjWX0avLf7YIpqJetIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-21T21:05:43Z"
    mac: ENC[AES256_GCM,data:GpLOgzn1hNrDjPtzZKYEFRcBWIS77oTEDL0z+T7v45DioQmRvoLnh/Ck/fyQWCBptNJAWasFtf6YbbxJAIblysV2Y13G+MNxNY2bEyjRQO3gu1DlLnIFuGg5Auqf4ZvgwY8r0AQCdIv22YA1sNz1PI/cP5xLA2GmoD5TQo37YPk=,iv:4gk0GgXky6LE97/DuyBzz3XCy5aVtvgwztBR6ECbD5E=,tag:Tq52MoSQofg4PGOmkueIog==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
