kube-prometheus-stack:
    prometheus:
        ingress:
            hosts:
                - ENC[AES256_GCM,data:H1md6jmsNCdMkcgF+3xHB6zUBNxz,iv:Upji9JUeLcmi3DpG9HLkQSgcIRy86mkq6It8eYZ/eBg=,tag:dYZtBfQXci9eV0FZcfWF9A==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:KJAXNNaxD6y6YS34CPKjWxg7qSij,iv:Faghsc+EA8w/L10ryU8HwqhlS2lCABR2GvGsOqpb18Y=,tag:EXw1GMaPGdwl8utveHdvxw==,type:str]
    alertmanager:
        ingress:
            hosts:
                - ENC[AES256_GCM,data:wShEEDlnLq+DtTPHTzw2Y/rsQz8d4wg=,iv:g3FT4qqIHuIP9Hc479kpTFIO+chqmKD2HmlQ+/evSa0=,tag:x0VHQBrLQikOz4SFm1pdDg==,type:str]
            tls:
                - hosts:
                    - ENC[AES256_GCM,data:eiulWNvDckQ+83xwCDxmYohoVaZJ29A=,iv:R7tW67IEqzMMuMU91HjLb20giOok5D0Uc8EkX03OaZM=,tag:dWBypoPHpRufoPgQnIyIaA==,type:str]
        config:
            receivers:
                - name: ENC[AES256_GCM,data:OdAnWBqYasqhMOezqa4=,iv:fgLTqggdYlWMh89xUNxFngQF4PIMvrDLdNg4siEvELI=,tag:rHJnhj0kjKzaNjjd6X1ieA==,type:str]
                  webhook_configs:
                    - url: ENC[AES256_GCM,data:MAH63YmHOCrMWO8PxVqyevQQu/w+SRnwOnLFBFQ7V4AkXJuApir0zFA4i8UW0bYERlkVxS2vTTo=,iv:X90DbBzpUhDZ9mwfRyTCtDuTdNv5TYExfwIbkwmgiqk=,tag:bJJfREPUya+t8mP4T63DQg==,type:str]
                      send_resolved: ENC[AES256_GCM,data:2L3/4Q==,iv:wt543sjclKsrnm/A699Q+T8+VGqauPOzg/lJPThQeRQ=,tag:9NRupkB7brF00Fc855fRUA==,type:bool]
                - name: ENC[AES256_GCM,data:khTMwQ==,iv:AAhUh1usBLXcK0SHD2OSoZG/lbJ6w5ji+qMEFVJ8hNA=,tag:ICwwd/p17Hi9bu7GBTNGiQ==,type:str]
                - name: ENC[AES256_GCM,data:Rv4FBmbX2Bc=,iv:5WcMZDUFGOKM9+v4dvERXm/YummGrqMJ58Qxh9qBA6U=,tag:9eoIMvQm6CkonzjyEKv44w==,type:str]
                  pushover_configs:
                    - token: ENC[AES256_GCM,data:Mey+Xb15yWH5MGVrHI/hQzlrZosMxakrYwul1lAH,iv:zr+vTL/CYybuofqx62O/Jpx6KBGKu7LzQfJ3N74aFjA=,tag:m1Zb2ZNC0pmlcnMPuvLvpQ==,type:str]
                      user_key: ENC[AES256_GCM,data:VKGaHqNdM4MfKREBMMn7sLZvJmOfMdllhnFA1bRr,iv:wdDLTth/Hz9uVwCeytNYmco/qUDXCjc6ZxHaalfpB38=,tag:iTkTMfNo8nrKN91QgW4fJQ==,type:str]
    kubeControllerManager:
        endpoints:
            - ENC[AES256_GCM,data:uIFhAfc3bYBBuoRq+A==,iv:M+dUNHIVOITZZNEYDUkULANgLYHmXNXkAG+tGOh0XG0=,tag:rpnsT1D1dLZptgRR67BwCQ==,type:str]
    kubeScheduler:
        endpoints:
            - ENC[AES256_GCM,data:PyxsmRhXkQM8qHlvDw==,iv:JuKhiRyVk9y7ogK7ji3WKRCGRC31tSQIUT1tl+fL92c=,tag:NyNWUzNJhlItj3jdwKQ0qg==,type:str]
    kubeProxy:
        endpoints:
            - ENC[AES256_GCM,data:L9mjSs45lq0/mDytvQ==,iv:dDGoEIrYB+pGIAwH6mv/jra375x8INdzKop4aR899yI=,tag:ndiYuMGRieGzAr2WowgKtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ksuvc69hvx8eup9g4g4m5lklhkmmmh4ddjdqfdsusaq50vu2846qu56ltl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJR2htMWlQZXNWNVE4emM5
            VTkxUnBVbWx4SUp3VjN0c2FIdnJTSzJ2Z204CmZPRGYwL1h3ZE1QVE5LaUZ3eE1M
            NVMzRXhCYVQwck83WGZzb0N5bElzSEkKLS0tIFIxcnBvL1RvdUIwWHQwUTRadnRF
            cEVCTTB6b1pSYit0elMyRFZ2RlhjSkUKXtoWVoe1cUoL5CsVzbF6lgp23aO8ixtj
            +9WH+V1DeAiWDe9JgdmJMm3GlJoh0UaLpEFOjWX0avLf7YIpqJetIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T08:41:37Z"
    mac: ENC[AES256_GCM,data:EW55WuO/wUnoMa2Vi+GZh2EGjqX4jvvOkPNka30EOP0h+69F7AVumqjob8/jbcsUOUA3DXUeQ7DGAIPVLMev3asaBoEaNoXfYTEu/e1QYQMqAYYoVQbueIDZHiXoIiunh4FYWMDFBXSHRsZGNpS1/JarQwWrpscPeu/3hsLVodY=,iv:5KFMrOf89h8pkorPDzi3bI0m/Y4w+T4ZE6jCDj24KXw=,tag:igTV7OspYiWmyoc9DtSy0g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
