---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recipes-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: recipes-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Recipes
        SECRET_KEY: "{{ `{{ .SECRET_TOKEN }}` }}"
        DB_ENGINE: "django.db.backends.postgresql"
        POSTGRES_PORT: "5432"
        POSTGRES_PASSWORD: "{{ `{{ .POSTGRES_PASS }}` }}"
        SOCIALACCOUNT_PROVIDERS: >-
          {
            "openid_connect": {
              "SERVERS": [
                {
                  "id": "authelia",
                  "name": "Authelia",
                  "server_url": "https://auth.{{ `{{ .homelab_domain }}` }}",
                  "APP": {
                    "client_id": "recipes",
                    "secret": "{{ `{{ .oidc_secret }}` }}"
                  }
                }
              ]
            }
          }
        # Postgres Init
        POSTGRES_DB: recipes
        POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        POSTGRES_SUPER_PASS: "{{ `{{ .POSTGRES_SUPER_PASS }}` }}"
        POSTGRES_SUPER_USER: "{{ `{{ .POSTGRES_SUPER_USER }}` }}"
        POSTGRES_PASS: "{{ `{{ .POSTGRES_PASS }}` }}"
        POSTGRES_USER: "{{ `{{ .POSTGRES_USER }}` }}"
  dataFrom:
    - extract:
        key: Recipes
        conversionStrategy: Default
        decodingStrategy: None
    - extract:
        key: cloudnative-pg
        conversionStrategy: Default
        decodingStrategy: None
    - extract:
        key: Homelab
        property: homelab_domain
        conversionStrategy: Default
        decodingStrategy: None
