---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-gateway-config
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: k8s-gateway-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        Corefile: |
          .:1053 {
            errors
            log
            health {
              lameduck 5s
            }
            ready
            k8s_gateway {{` {{ .homelab_domain }} `}} {
              apex  k8s-gateway.network
              resources Ingress Service
              ttl 300
            }
            prometheus 0.0.0.0:9153
            loop
            reload
            loadbalance
          }
  dataFrom:
    - extract:
        key: Homelab
        property: homelab_domain
        conversionStrategy: Default
        decodingStrategy: None
