---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  # Create can not be restricted to a resource name.
  verbs: ["create"]
- apiGroups: [""] # "" indicates the core API group
  resourceNames: ["tailscale-auth"]
  resources: ["secrets"]
  verbs: ["get", "update", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "tailscale"
  namespace: "valheim"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "tailscale"
  namespace: "home-assistant"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "tailscale"
  namespace: "networking"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale
subjects:
- kind: ServiceAccount
  name: "tailscale"
  namespace: "valheim"
- kind: ServiceAccount
  name: "tailscale"
  namespace: "home-assistant"
- kind: ServiceAccount
  name: "tailscale"
  namespace: "networking"
roleRef:
  kind: ClusterRole
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
