---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: tailscale
spec:
  externalSecretName: tailscale-auth
  namespaceSelector:
    matchLabels: 
      tailscale: "true"
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword-connect
    target:
      name: tailscale-auth
      creationPolicy: Owner
    dataFrom:
      - extract:
          conversionStrategy: Default
          decodingStrategy: None
          # TS_AUTHKEY
          key: Tailscale
